<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [ ]:
# Basics of Python lists, arrays, and dictionaries.

In [1]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [2]:
# These are lists:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
# These are arrays:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
# This is a dictionary:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [ ]:
# Unlike sets in mathematics, order matters in lists and arrays.

## 1.2 Accessing data from a list (or array)

In [ ]:
# The simplest way to retrieve data from a list (or an array) is through indexing.
# It's a good practice to remember that index in CS always starts from 0.

In [7]:
py_real_names[0]

'Natasha Romanoff'

In [6]:
py_super_names[0]

'Black Widow'

In [ ]:
# One drawback of ordinary forward indexing is that one must know the size of the list or array. 
# To save effort, backward indexing comes to the rescue. 
# The last element in a list or an array is always indexed as -1.

In [8]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [ ]:
# Data are stored in dictionaries as 'key-value' pairs. 
# This gives dictionary the advantage of extracting value solely from its corresponding key. 
# For example:

In [9]:
superhero_info["Natasha Romanoff"]

'Black Widow'

In [ ]:
# Collections of all keys and values can also be retrieved separately. 

In [10]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [13]:
type(superhero_info.keys()) # Notice that the class of the collection of all keys is NOT a list. 

dict_keys

In [12]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

In [14]:
type(superhero_info.values()) # The same goes for the collection of all values. 

dict_values

## 1.4 Higher dimensional lists

In [ ]:
# A list in Python is not confined to 1D. 
# If a list were to be interpreted as a vector, then a 2D list can be thought of as a matrix. A nD list is \
#     analogous to a nD tensor. 
# The dimension of a given list can be seen from the number of '[' at the very beginning.

In [ ]:
# For example: 
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']] # This is a 2D list because there are 2 '[' in the front.

# 2 Lists vs. Arrays

## 2.1 Size

In [ ]:
# An array can be created from a list.
# Arrays have shape, lists have length (retrieved with len()).

In [15]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list to create a NEW NumPy array

In [17]:
len(py_list_2d)

10

In [18]:
len(np_array_2d)

10

In [19]:
np_array_2d.shape

(10, 2)

In [ ]:
# Notice that len() is a method, it has () following it. 
# Whereas .shape is an attribute, it does not have () following it.
# len() only returns the first level length, whereas .shape returns the entire structure of an array. 
# lists have no attribute .shape, therefore, py_list_2d.shape will raise an error.

In [20]:
py_list_2d.shape

AttributeError: 'list' object has no attribute 'shape'

## 2.2 Arrays are fussy about type

In [ ]:
# Within a list, elements can be of different data types. 
# Whereas in arrays, elements must be of the same data type. 

In [21]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [22]:
py_list

[1, 1.5, 'A']

In [23]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [ ]:
# When operating on lists, Python considers list as a wholistic entity. 
# Whereas when operating on array, Python performs element-wise operation on each of the element of that array. 

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [25]:
py_list + 10        # Won't work! You cannot add an object of class 'list' to an object of class 'int'.

TypeError: can only concatenate list (not "int") to list

In [26]:
np_array + 10    # But this works.

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

In [27]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [28]:
py_list_1 + py_list_2   # This merges the two lists. 

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [29]:
np_array_1 + np_array_2   # This performs element-wise operation.

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [31]:
py_list*2     # This repeats the same list twice (expanding the list).

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [32]:
np_array*2    # Again, this performs element-wise operation. 

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [34]:
py_list**2    # Similarly, this won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [35]:
np_array**2   # But this works.

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [37]:
py_list == 3     # This works, because a list is not equal to an integer. 

False

In [38]:
np_array == 3  

array([False, False,  True, False, False])

In [39]:
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [ ]:
# More examples:

In [43]:
print(sum(py_list),    # sum() is a base Python function
max(py_list),     # max() is a base Python function
min(py_list),     # min() is a base Python function
np_array.sum(),
np_array.max(),
np_array.min(),
np_array.mean(),
np_array.std())

15 5 1 15 5 1 3.0 1.4142135623730951
